[project]
name = "rent-cars-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-cli>=0.0.16",
    "fastapi[standard]>=0.121.2",
    "sqlmodel[postgresql]>=0.0.27",
]
